### PR TITLE
fix: support human-readable uuid in serde.

### LINKED ISSUE #73: serde_json::to_string serialize uuid type into string
Hi, below is my struct definition for `uuid_test` table:

```rust
#[derive(Debug, Serialize, Deserialize, Row)]
pub struct Test {
    #[serde(with = "clickhouse::serde::uuid")]
    pub uuid: Uuid,
    pub name: String,
}

pub async fn create_table(client: &Client) -> Result<(), Box<dyn std::error::Error>> {
    client
        .query(
            "
            CREATE TABLE IF NOT EXISTS uuid_test(
                uuid UUID,
                name LowCardinality(String)
            )
            ENGINE = MergeTree
            ORDER BY name
        ",
        )
        .execute()
        .await
        .map_err(|err: Error| err.into())
}


pub async fn get_by_uuid(client: &Client, uuid: &Uuid) -> Result<Test, Box<dyn std::error::Error>> {
    let test = client
        .query("SELECT ?fields FROM uuid_test WHERE uuid = ?")
        .bind(uuid)
        .fetch_one::<Test>()
        .await?;

    println!("[debug]Got test: {test:#?}");

    Ok(test)
}
```

I used `serde_json` to serialize `Test` into string but uuid was output in array type:

```rust
let uuid = "...";
let test = get_by_uuid(&db, &uuid).await.unwrap();
let s = serde_json::to_string(&test).unwrap();
println(s);
```

Here is the output:

```json
{"uuid":[214,64,245,20,199,106,26,34,103,164,208,2,209,231,100,162],"name":"Test"}
```

How could I serialize uuid into string type?

Thanks

### PR DESCRIPTION
**Pull request by fky2015**
UUID should be serialized into a more human-readable format when working with JSON.
This commit fixes #73.

### CODE REVIEW

File: src/serde.rs [hunk 1]
```diff
@@ -85,18 +86,27 @@ pub mod uuid {
...
 
     pub fn deserialize<'de, D>(deserializer: D) -> Result<Uuid, D::Error>
     where
         D: Deserializer<'de>,
     {
-        let mut bytes: [u8; 16] = Deserialize::deserialize(deserializer)?;
-        transform(&mut bytes);
-        Ok(Uuid::from_bytes(bytes))
+        if deserializer.is_human_readable() {
+            let uuid_str: String = Deserialize::deserialize(deserializer)?;
```
Comment (loyd) [inline src/serde.rs:103]: Can we use `&str` here?

**Comment by loyd** [comment]
I apologize for the inadequately long answer. Thanks for your contribution. LGTM. Can you update PR? If you don't have time, it's OK, and I'll update it on my own.

File: Cargo.toml [hunk 2]
```diff
@@ -93,6 +93,8 @@ tokio = { version = "1.0.1", features = ["full", "test-util"] }
 hyper = { version = "1.1", features = ["server"] }
 serde_bytes = "0.11.4"
 serde_repr = "0.1.7"
-uuid = { version = "1", features = ["v4"] }
+serde_json = "1.0.68"
+uuid = { version = "1", features = ["v4", "serde"] }
+function_name = "0.3"
```
Comment (serprex) [inline Cargo.toml:98]:
```suggestion
uuid = { version = "1", features = ["v4", "serde"] }
```
Can these dependencies be skipped?

**Review by serprex — APPROVED** [review]

**Review by heavycrystal — APPROVED** [review]
